name: Build texlive-full(base)

on:
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: rahulraman0108/texlive-full
  IMAGE_TAG: base

jobs:
  build-base-image:
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm64]
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
            platform_pair: linux_amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            platform_pair: linux_arm64
    runs-on: ${{ matrix.runner }}
    name: Build base image for ${{ matrix.platform }}
    continue-on-error: true

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main
        with:
          submodules: true
          token: ${{ secrets.PA_TOKEN }}

      - name: Update for Latest
        run: |
          # 更新submodules
          git submodule update --remote --recursive
          tree .

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,enable=true,value=${{ env.IMAGE_TAG }}

      - name: Clean runner for Docker builds
        uses: sctg-development/clean-image-for-docker@v2
        with:
          remove-development-tools: "true"
          remove-browsers: "true"
          remove-databases: "true"
          remove-cloud-tools: "true"
          remove-testing-tools: "true"
          remove-documentation: "true"
          remove-android: "true"
          remove-cached-tools: "true"
          show-top-packages: "true"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image by digest
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          cache-from: type=gha,scope=${{ github.workflow }}-${{ matrix.platform_pair }}
          cache-to: type=gha,scope=${{ github.workflow }}-${{ matrix.platform_pair }},mode=max
          context: texlive/Base
          file: texlive/Base/Dockerfile
          # push: true
          labels: ${{ steps.meta.outputs.labels }}
          # tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.docker_build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.platform_pair }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge-base-image:
    runs-on: ubuntu-latest
    name: Merge and push base image
    needs:
      - build-base-image
    if: always()
    continue-on-error: true

    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Login to Docker Hub Registry'
        uses: docker/login-action@v3.0.0
        with:
          registry: docker.io
          username: rahulraman0108
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create -t ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            -t docker.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            $(printf '${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect \
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  push-slim-image:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
            tag: 2024.1.slim
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            tag: 2024.1.slim-arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Login to Docker Hub Registry'
        uses: docker/login-action@v3.0.0
        with:
          registry: docker.io
          username: rahulraman0108
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Clean runner for Docker builds
        uses: sctg-development/clean-image-for-docker@v2
        with:
          remove-development-tools: "true"
          remove-browsers: "true"
          remove-databases: "true"
          remove-cloud-tools: "true"
          remove-testing-tools: "true"
          remove-documentation: "true"
          remove-android: "true"
          remove-cached-tools: "true"
          show-top-packages: "true"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5.1.0
        with:
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha
          context: texlive/Slim
          file: texlive/Slim/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}
            docker.io/${{ env.IMAGE_NAME }}:${{ matrix.tag }}
