name: Clean Image(texlive-full)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  
    # run every week

jobs:
  clean-ghcr-texlive:
    runs-on: ubuntu-latest
    steps:
      - name: Delete 'untaged' containers
        uses: snok/container-retention-policy@v2
        with:
          account-type: personal
          # account: rahulraman0108
          image-names: texlive-full/*, texlive-full
          cut-off: 1 days ago UTC
          untagged-only: true
          token: ${{ secrets.PA_TOKEN }}
