name: Clean Image(texlive-full)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  
    # run every week

jobs:
  clean-ghcr-texlive:
    runs-on: ubuntu-latest
    steps:
      - name: Delete 'untaged' containers
        uses: snok/container-retention-policy@v2
        with:
          image-names: texlive-full/*,texlive-full
          cut-off: 1 min ago UTC
          account-type: org
          org-name: rahulraman0108
          untagged-only: true
          token: ${{ secrets.ORGTOKEN }}