name: Build texlive-full(ghcr)

on:
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: rahulraman0108/texlive-full
  # IMAGE_TAG: base

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        tex-version: [2020, 2021, 2022, 2023, 2024, 2025]
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx for multi-platform builds
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5.1.0
        with:
          platforms: linux/amd64,linux/arm64
          context: texlive/${{ matrix.tex-version }}
          file: texlive/${{ matrix.tex-version }}/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tex-version }}.1
